version: "3.9"

services:
  web:
    build: .
    entrypoint: gunicorn
    command:
      - "approval_polls.wsgi:application"
      - "-b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
      - ./db.sqlite3:/data/db.sqlite3
