version: "3.9"

services:
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=abcd12345
    ports:
      - "8000:8000"
    depends_on:
      - db
