# fly.toml app configuration file generated for vote-electionscience-org on 2024-01-27T11:17:40-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vote-electionscience-org'
primary_region = 'sjc'
console_command = '/code/manage.py shell'

[build]

[env]
PORT = '8000'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
kind = 'shared-cpu-2x'
memory_mb = 512

[[statics]]
guest_path = '/code/static'
url_prefix = '/static/'

[mounts]
source = "litefs"
destination = "/data"
