[tool.poetry]
name = "approval-frame"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{ include = "approval_frame" }]

[tool.poetry.dependencies]
python = "^3.8"
django = "~2.0"
django-registration-redux = "2"
dj-static = "^0.0.6"
pytz = "^2015.7"
python-social-auth = "^0.3.6"
mailchimp = "^2.0.9"
django-extensions = "^1.7.9"
djangoajax = "^3"
python-dotenv = "^0.18.0"
social-auth-app-django = "5.00"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
