[tool.poetry]
name = "approval-frame"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.9"
django = "1.11.29"
django-registration-redux = "1.9"
dj-static = "0.0.6"
pytz = "2015.7"
python-openid = "2.2.5"
# requests-oauthlib = "0.6.0"
mailchimp = "2.0.9"
django-extensions = "1.7.9"
djangoajax = "2.3.7"
python-dotenv = "0.18.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
