[tool.poetry]
name = "approval-frame"
version = "0.1.0"
description = ""
authors = ["Felix Sargent <felix@electionscience.org>"]
readme = "README.md"
packages = [{ include = "approval_polls" }]

[tool.poetry.dependencies]
python = "^3.11"
django = "^5"
django-registration-redux = "^2.9"
dj-static = "^0.0.6"
pytz = "^2023.4"
python-openid = "^2.2.5"
django-extensions = "^3.2.3"
djangoajax = "^3.3"
django-environ = "^0.11.2"
django-sendgrid-v5 = "^1.2.3"
gunicorn = "^21.2.0"
django-upgrade = "^1.15.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
