FROM python:3.8.16

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1
ENV POETRY_HOME=/etc/poetry

# Install pip requirements
COPY ../pyproject.toml ../poetry.lock .
RUN curl -sSL https://install.python-poetry.org |  python3 -
RUN /etc/poetry/bin/poetry install

WORKDIR /app
COPY ../ /app

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
# File wsgi.py was not found. Please enter the Python path to wsgi file.
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "testproject.wsgi"]